### ISSUE TITLE
Issue with Database Queries in Authenticated Django API Calls despite JWT Verification

### ISSUE THREAD

**Issue by anusreesoumya** [AbhiSaphire/Django-DiscussionForum#1]
Each time an authorized API call is made using a bearer token (specifically a simple JWT), a database query is executed to retrieve user details, even though JWT Authentication is supposed to eliminate the need for database validation. Could someone help me understand the reason behind these database queries and suggest a solution to avoid them while still ensuring proper authentication through JWT? Your insights would be greatly appreciated!

When making a request to a Django API with a JWT bearer token, an extra database call is initiated to retrieve user details associated with the user ID specified in the token payload. SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2 LIMIT 21; args=(2,); alias=default . The execution of this database query is unexpected, and I am unsure about the reason for its occurrence. Can anyone assist me in determining the cause of this DB Query?

**Comment by AbhiSaphire** [comment]
Hi @anusreesoumya,

You're right about JWT authentication aiming to minimize database validations. If you're observing an unexpected database call when using the JWT bearer token for the new_topic API, it's likely due to the code fetching user details from the database instead of utilizing the information from the JWT token payload. In your API code, replace `user = User.objects.first()` with `user = request.user` to eliminate the extra database query. 
This adjustment ensures that user information is retrieved from the JWT payload, removing the need for an additional database call. Just confirm that your JWT is configured to include the required user details during the authentication process.

Best regards,
Abhishek

**Comment by anusreesoumya** [comment]
Hi , @AbhiSaphire ,
I want my APIs to operate without requiring any user details. However, I've noticed that the database query for user information is being generated in all API calls. As an example, in the API view I attempted, I observed the inclusion of this database query for user details. The sample API view I tried is below:

class TestView(ViewSet):
    permission_classes = (IsAuthenticated,)
    def list(self, request):
        return Response({'Key': 'Test '})
